services:
  - type: web
    name: sales-rep-logger
    env: node
    plan: free
    buildCommand: "npm install && cd frontend && npm install && npm run build"
    startCommand: "node backend/server.js"
    branch: main